### ISSUE TITLE
npm start 出现的错误

### ISSUE THREAD

**Issue by moxun33** [thundernet8/StarCabinet#10]
node Version: v6.11.0
npm Version v3.10.10

按照提示，运行npm rebuild也是不行

```bash
App threw an error during load
Error: Cannot open /Library/WebServer/Documents/electron/StarCabinet-master/node_modules/keytar/build/Release/keytar.node: Error: The module '/Library/WebServer/Documents/electron/StarCabinet-master/node_modules/keytar/build/Release/keytar.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.<anonymous> (/Library/WebServer/Documents/electron/StarCabinet-master/dist/electron.js:11852:207)
    at Object.<anonymous> (/Library/WebServer/Documents/electron/StarCabinet-master/dist/electron.js:11853:30)
    at __webpack_require__ (/Library/WebServer/Documents/electron/StarCabinet-master/dist/electron.js:660:30)
    at fn (/Library/WebServer/Documents/electron/StarCabinet-master/dist/electron.js:86:20)
    at Object.<anonymous> (/Library/WebServer/Documents/electron/StarCabinet-master/dist/electron.js:11760:12)
    at Object.<anonymous> (/Library/WebServer/Documents/electron/StarCabinet-master/dist/electron.js:11814:4)
    at __webpack_require__ (/Library/WebServer/Documents/electron/StarCabinet-master/dist/electron.js:660:30)
    at fn (/Library/WebServer/Documents/electron/StarCabinet-master/dist/electron.js:86:20)
    at Object.defineProperty.value (/Library/WebServer/Documents/electron/StarCabinet-master/dist/electron.js:11053:14)
    at __webpack_require__ (/Library/WebServer/Documents/electron/StarCabinet-master/dist/electron.js:660:30)
2017-06-27 16:28:40.207 Electron[62944:1580846] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (1.72 secs).
GVA error: Not detecting IGPU in IORegistry!
GVA error: Not detecting valid offline codec!
GVA info: Successfully connected to the Intel plugin, offline Gen6
AVDCreateGPUAccelerator: Error loading GPU renderer
```

**Comment by moxun33** [comment]
Steps for mac:
npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild

**Comment by thundernet8** [comment]
@moxun33 OK
