### ISSUE TITLE
运行不起来!!

### ISSUE THREAD

**Issue by sgli** [thundernet8/StarCabinet#18]
该如何运行? 

键入npm run start:dev 发生如下异常 : 

E:\WorkSpace\WorkSpace_GitHub\StarCabinet-master>npm run start:dev

> starcabinet@2.0.0 start:dev E:\WorkSpace\WorkSpace_GitHub\StarCabinet-master
> cross-env NODE_ENV=development electron ./app

App threw an error during load
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\E:\WorkSpace\WorkSpace_GitHub\StarCabinet-master\node_modules\keytar\build\Release\keytar.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\WorkSpace\WorkSpace_GitHub\StarCabinet-master\node_modules\keytar\lib\keytar.js:1:169)
    at Object.<anonymous> (E:\WorkSpace\WorkSpace_GitHub\StarCabinet-master\node_modules\keytar\lib\keytar.js:61:3)

**Comment by lou1swu** [comment]
rebuild一下
